<table>
          <tr>
            <td>
              <span class="add-on"><i class="icon-company" ></i></span>
              <span>Thương hiệu: </span>
            </td>
            <td><input type="text" id="brand" name="brand" disabled required="required" value="<?php echo $tire_brand ?>" /></td>
          </tr>
          <tr>
            <td>
              <span class="add-on"><i class="icon-resize-full" ></i></span>
              <span>Kích cỡ: </span>
            </td>
            <td><input type="text" id="size" name="size" disabled required="required" value="<?php echo $tire_size ?>" /></td>
          </tr>
          <tr>
            <td>
              <span class="add-on"><i class="icon-barcode" ></i></span>
              <span>Mã gai: </span>
            </td>
            <td><input type="text" id="pattern" name="pattern" disabled required="required" value="<?php echo $tire_pattern ?>" /></td>
          </tr>
        </table>
        <table class="table_data">
          <thead>
            <tr>
              <th class="fix">Ngày</th>
              <th class="fix">Code</th>
              <th class="fix">Brand</th>
              <th class="fix">Size</th>
              <th class="fix">Pattern</th>
              <th class="fix">SL</th>
            </tr>
          </thead>
          <tbody>
            <?php
            foreach ($tire_goings as $tire_going) {
            ?>
            <tr>
              <td class="fix"><?php echo $lib->hien_thi_ngay_thang($tire_going->import_tire_order_date) ?></td>
              <td class="fix"><?php echo $tire_going->import_tire_order_code ?></td>
              <td class="fix"><?php echo $tire_going->tire_brand_name ?></td>
              <td class="fix"><?php echo $tire_going->tire_size_number ?></td>
              <td class="fix"><?php echo $tire_going->tire_pattern_name ?></td>
              <td class="fix"><?php echo $tire_going->tire_number ?></td>
            </tr>
            <?php } ?>
          </tbody>
          
        </table>
        <div id="error" class="error"></div>
