<?php
$url_order = 'ASC';
if ($order_by == 'tire_price_agent_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'tire_brand_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'tire_size_number')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'tire_pattern_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>

<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> BẢNG GIÁ ĐẠI LÝ</h1></center>
<div class="add-box">
    <a class="add_button" onClick="add_click();">Nhập mới</a>
    <a class="add_button" id="import_excel" href="<?= $this->url('tirepriceagent/import')?>">Import Excel</a>
    <a class="add_button" id="btnExport" >Export Excel</a>
</div>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Search">
        <input type="button" name="" id="search-submit" class="button-search" value="Search" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
       
    </div>
    <div class="tablenav top">

    	<div class="alignleft actions">
			<select name="action" id="action">
            	<option value="-1" selected="selected">Select</option>
                
                <option value="delete">Delete</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Apply" onclick="action();">
		</div>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">All</option>
			<option value="15">15 items</option>
            <option value="20">20 items</option>
            <option value="50">50 items</option>
            <option selected="selected" value="100">100 items</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Apply" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>

        
      </div>

</div>

<table class="table_data" id="tblExport">
<thead>
    <tr>
        <th class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_price_agent_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'tire_price_agent_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_name','<?php echo $url_order ?>')">Đại lý <?php if ($order_by == 'customer_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_brand_name','<?php echo $url_order ?>')">Thương hiệu <?php if ($order_by == 'tire_brand_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_size_number','<?php echo $url_order ?>')">Kích cỡ <?php if ($order_by == 'tire_size_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_pattern_name','<?php echo $url_order ?>')">Mã gai <?php if ($order_by == 'tire_pattern_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_price','<?php echo $url_order ?>')">Giá <?php if ($order_by == 'tire_price'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','start_date','<?php echo $url_order ?>')">Từ ngày <?php if ($order_by == 'start_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','end_date','<?php echo $url_order ?>')">Đến ngày <?php if ($order_by == 'end_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th class="fix"></th>
    </tr>
    
   </thead>
   <tbody>
    <?php foreach ($tires as $tire) : ?>
    
        
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $tire->tire_price_agent_id ?>" class="edit_tr">
            
            <td>
                <input name="check[]" type="checkbox" class="checkbox" value="<?php echo $tire->tire_price_agent_id ?>">
            </td>
            
            <td  class="fix"><?php echo $i++; ?></td>
            <td class="fix" id="customer_<?php echo $tire->tire_price_agent_id; ?>"><?php echo $tire->customer_name; ?></td>
            <td class="fix" id="tire_brand_<?php echo $tire->tire_price_agent_id; ?>"><?php echo $tire->tire_brand_name; ?></td>
            <td class="fix" id="tire_size_<?php echo $tire->tire_price_agent_id; ?>"><?php echo $tire->tire_size_number; ?></td>
            <td class="fix" id="tire_pattern_<?php echo $tire->tire_price_agent_id; ?>"><?php echo $tire->tire_pattern_name; ?></td>
            <td class="fix" id="tire_price_<?php echo $tire->tire_price_agent_id; ?>"><?php echo $lib->formatMoney($tire->tire_price); ?></td>
            
            <td class="fix" id="start_date_<?php echo $tire->tire_price_agent_id; ?>"><?php echo $lib->hien_thi_ngay_thang($tire->start_date); ?></td>
            <td class="fix" id="end_date_<?php echo $tire->tire_price_agent_id; ?>"><?php echo $lib->hien_thi_ngay_thang($tire->end_date); ?></td>
            <td>
                <button class="error" onclick="del(<?php echo $tire->tire_price_agent_id ?>)" >Xóa</button>
                
               
            </td>
        </tr>


    <?php endforeach; ?>
     
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
<div style="display:none" id="lasted"></div>
<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

<div class="add-field">
        <fieldset class="groupbox">
            <legend>
                <span><h3>Bảng giá </h3></span>
            </legend>
            <div class="login_body">
                  <form id="add_tire" method="post" action="">
                      <table style="margin-top:0px;width:100%">
                        <tr>
                            
                            <td>Thương hiệu</td>
                            <td>
                                <select name="tire_brand" id="tire_brand" tabindex="1"  required="required">
                                    <?php foreach ($tire_brands as $tire_brand) { ?>
                                    <option value="<?php echo $tire_brand->tire_brand_id ?>"><?php echo $tire_brand->tire_brand_name ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                            <td>Kích cỡ</td>
                            <td>
                                <select name="tire_size" id="tire_size" tabindex="2"  required="required">
                                    <?php foreach ($tire_sizes as $tire_size) { ?>
                                    <option value="<?php echo $tire_size->tire_size_id ?>"><?php echo $tire_size->tire_size_number ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                            <td>Mã gai</td>
                            <td>
                                <select name="tire_pattern" id="tire_pattern" tabindex="3"  required="required">
                                    <?php foreach ($tire_patterns as $tire_pattern) { ?>
                                    <option value="<?php echo $tire_pattern->tire_pattern_id ?>"><?php echo $tire_pattern->tire_pattern_name ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td>Giá</td>
                            <td><input  type="text" class="numbers" id="tire_price"  name="tire_price" tabindex="6"  required="required" ></td>
                            
                            <td>Từ ngày</td>
                            <td>
                                <input  type="text" class="ngay" id="start_date"  name="start_date" tabindex="4"  required="required" >
                            </td>
                            <td>Đến ngày</td>
                            <td>
                                <input  type="text" class="ngay" id="end_date"  name="end_date" tabindex="5"  required="required" >
                            </td>
                        </tr>
                        <tr>
                            <td>Đại lý</td>
                            <td>
                                <select name="customer" id="customer" tabindex="7"  required="required">
                                    <?php foreach ($customers as $customer) { ?>
                                    <option value="<?php echo $customer->customer_id ?>"><?php echo $customer->customer_name ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                        </tr>
                        
                        <tr>
                            <td>&nbsp;</td>
                            <td><input type="hidden" readonly id="yes" name="yes" required="required" ></td>
                            <td>&nbsp;</td>
                        </tr>
                        
                        
                         <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>
                                <input type="submit" name="submit" value="Submit" tabindex="8">
                                
                            </td>
                            <td>
                                <input type="reset" name="reset" value="Reset" tabindex="9">
                            </td>
                             
                        </tr>
                    </table> 
                </form>
            </div>
        </fieldset>
    </div>


<script type="text/javascript">


  
$('.add-field').hide();  


$('html').click(function(e) {
    if(e.target == '[object HTMLDivElement]' || e.target == '[object HTMLBodyElement]') {
        $('.add-field').slideUp(500);   
    }
    
});



    $('.edit_tr').click(function(e){
        if(e.target != '[object HTMLButtonElement]' && e.target != '[object HTMLSpanElement]' && !$('.checkbox').is(':focus')) { 
            if(!$('.checkbox').is(':focus')){
                $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
            }
            
            var tire_brand = $(this).find("#tire_brand_"+$(this).attr('id')).text();
            var tire_size = $(this).find("#tire_size_"+$(this).attr('id')).text();
            var tire_pattern = $(this).find("#tire_pattern_"+$(this).attr('id')).text();
            var tire_price = $(this).find("#tire_price_"+$(this).attr('id')).text();
            var start = $(this).find("#start_date_"+$(this).attr('id')).text();
            var end = $(this).find("#end_date_"+$(this).attr('id')).text();
            var customer = $(this).find("#customer_"+$(this).attr('id')).text();
            //alert(cost_code);
            $('#yes').val($(this).attr('id'));
            
            $('#tire_brand option:contains('+tire_brand+')').attr('selected','selected');
            $('#tire_size option:contains('+tire_size+')').attr('selected','selected');
            $('#tire_pattern option:contains('+tire_pattern+')').attr('selected','selected');
            $('#tire_price').val(tire_price);
            $('#start_date').val(start.replace(/\//g,"-"));
            $('#end_date').val(end.replace(/\//g,"-"));
            $('#customer option:contains('+customer+')').attr('selected','selected');

            $( ".add-field" ).dialog( "open" );
        }

        
        
    });


</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
     $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   
     
        $('#tire_price').val(0);
        $('#start_date').val("");
        $('#end_date').val("");
                
        $('.numbers').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.numbers').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });

    $( ".add-field" ).dialog( "open" );
}


$(document).ready(function(){
            // Validate form
            $("#add_tire").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    var tire_brand = $('#tire_brand').attr('value');
                    var tire_size = $('#tire_size').attr('value');
                    var tire_pattern = $('#tire_pattern').attr('value');
                    var tire_price = $('#tire_price').attr('value');
                    var start_date = $('#start_date').attr('value');
                    var end_date = $('#end_date').attr('value');
                    var customer = $('#customer').attr('value');

                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/tirepriceagent/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            
                            tire_brand: tire_brand,
                            tire_size: tire_size,
                            tire_pattern: tire_pattern,
                            tire_price: tire_price,
                            start_date: start_date,
                            end_date: end_date,
                            customer: customer,
                            yes: yes,

                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            //alert(answer);
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

                            }
                            else{
                                setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                
                            }
                        }
                    });
                    return false;
                     
                 }
            });


});

</script>
<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

$("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:300,
            width:400,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });


 
var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');


</script>
</div>

<script type="text/javascript">


$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Bảng giá",
    hide: 'fold',
    show: 'blind'
});


var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+5",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onSelect: function(dateStr) {
          if ($('#end_date').val()=="") {
            var d = $.datepicker.parseDate('dd-mm-yy', dateStr);
            //var years = parseInt(10, 10);

            //d.setFullYear(d.getFullYear() + years);

            $('#end_date').datepicker('setDate', d);
          }
            
        },
        onClose: function(selectedDate) {
                
                $( "#end_date" ).datepicker( "option", "minDate", selectedDate );

         },
    }; 
    $("#start_date").datepicker(pickerOpts);

    var pickerOpts2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+5",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#start_date" ).datepicker( "option", "maxDate", selectedDate );

         },
    }; 
    $("#end_date").datepicker(pickerOpts2);

$('.numbers').keyup(function(event) {

      // skip for arrow keys
  if(event.which >= 37 && event.which <= 40) return;

  // format number
  $(this).val(function(index, value) {
    return value
      .replace(/\D/g, "")
      .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
    ;
  });
});
</script>

