<?php
$sum_arr = array();
$go_arr = array();
$tongorder = 0;
$tongdangve = 0;
?>
<center style="clear:both;"><h1>BẢNG THEO DÕI</h1></center>
<a class="add_button" href="<?php echo $this->url('stockanalytics/export') ?>" >Export Excel</a>
<div class="add-box thongtin" style="text-align:center;width:20%">
  <table class="table_data_edit">
    <tr>
      <th>SL cont nhập</th>
      <th>Tỷ lệ</th>
    </tr>
    <tr>
      <td><?php echo $lib->formatMoney($total_cont) ?></td>
      <td><?php echo $lib->formatMoney($total_cont*100/120,2) ?>%</td>
    </tr>
  </table>
</div>
<div style="clear: both;"></div>
<div class="report">
    <div class="report-left">
                    <table class="table_data_edit">
                        <thead>
                            <tr>
                                <th colspan="3" class="fix">GOODRIDE</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/CR926.jpg" width="30" height="30" /></td>
                                <td class="fix">7.50R16</td>
                                <td class="fix">CR926</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/CL946.jpg" width="30" height="30" /></td>
                                <td class="fix">9.00-20</td>
                                <td class="fix">CL946</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/CR926.jpg" width="30" height="30" /></td>
                                <td class="fix">10.00R20</td>
                                <td class="fix">CR926</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/CR926.jpg" width="30" height="30" /></td>
                                <td class="fix">11.00R20</td>
                                <td class="fix">CR926</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/CR976A.jpg" width="30" height="30" /></td>
                                <td class="fix">11.00R20</td>
                                <td class="fix">CR976A</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/CM987.jpg" width="30" height="30" /></td>
                                <td class="fix">11.00R20</td>
                                <td class="fix">CM987</td>
                            </tr>
                            
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/CR926.jpg" width="30" height="30" /></td>
                                <td class="fix">12.00R20</td>
                                <td class="fix">CR926</td>
                            </tr>
                            
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/CR976A.jpg" width="30" height="30" /></td>
                                <td class="fix">11R22.5</td>
                                <td class="fix">CR976A</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/AS668.jpg" width="30" height="30" /></td>
                                <td class="fix">11R22.5</td>
                                <td class="fix">AS668</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/CM983.jpg" width="30" height="30" /></td>
                                <td class="fix">11R22.5</td>
                                <td class="fix">CM983</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/CR960A.jpg" width="30" height="30" /></td>
                                <td class="fix">295/75R22.5</td>
                                <td class="fix">CR960A</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/CM983.jpg" width="30" height="30" /></td>
                                <td class="fix">295/75R22.5</td>
                                <td class="fix">CM983</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/CR926.jpg" width="30" height="30" /></td>
                                <td class="fix">12R22.5</td>
                                <td class="fix">CR926</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/CR976A.jpg" width="30" height="30" /></td>
                                <td class="fix">12R22.5</td>
                                <td class="fix">CR976A</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/AS668.jpg" width="30" height="30" /></td>
                                <td class="fix">12R22.5</td>
                                <td class="fix">AS668</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/MD738.jpg" width="30" height="30" /></td>
                                <td class="fix">12R22.5</td>
                                <td class="fix">MD738</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/CM985.jpg" width="30" height="30" /></td>
                                <td class="fix">12R22.5</td>
                                <td class="fix">CM985</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/CB919.jpg" width="30" height="30" /></td>
                                <td class="fix">12R22.5</td>
                                <td class="fix">CB919</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/CB972.jpg" width="30" height="30" /></td>
                                <td class="fix">11.00R20</td>
                                <td class="fix">CB972</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/CM958.jpg" width="30" height="30" /></td>
                                <td class="fix">12.00R20</td>
                                <td class="fix">CM958</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/CM913A.jpg" width="30" height="30" /></td>
                                <td class="fix">12.00R20</td>
                                <td class="fix">CM913A</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/EZ356.jpg" width="30" height="30" /></td>
                                <td class="fix">12.00R20</td>
                                <td class="fix">EZ356</td>
                            </tr>
                            <tr>
                                <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/CB919.jpg" width="30" height="30" /></td>
                                <td class="fix">12.00R20</td>
                                <td class="fix">CB919</td>
                            </tr>
                            <tr style="font-weight: bold;">
                                <td colspan="3" class="fix">Tổng cộng</td>
                            </tr>
                        </tbody>
                       
                    </table>
                </div>
            
                <div class="report-right">
                    <div style="float:left">
                        <table class="table_data_edit">
                            <thead>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <th class="fix show_order"><?php echo date('m',$month) ?></th>
                                    <?php 
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <th style="background: rgba(255, 0, 0, 0.2)" class="fix" id="show_order">Tổng order</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t1 = isset($hangorder[date('m-Y',$month)]['Goodride7.50R16CR926'])?$hangorder[date('m-Y',$month)]['Goodride7.50R16CR926']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride7.50R16CR926'] = isset($sum_arr['Goodride7.50R16CR926'])?$sum_arr['Goodride7.50R16CR926']+$t1:$t1;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride7.50R16CR926']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t19 = isset($hangorder[date('m-Y',$month)]['Goodride9.00-20CL946'])?$hangorder[date('m-Y',$month)]['Goodride9.00-20CL946']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride9.00-20CL946'] = isset($sum_arr['Goodride9.00-20CL946'])?$sum_arr['Goodride9.00-20CL946']+$t19:$t19;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride9.00-20CL946']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t2 = isset($hangorder[date('m-Y',$month)]['Goodride10.00R20CR926'])?$hangorder[date('m-Y',$month)]['Goodride10.00R20CR926']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride10.00R20CR926'] = isset($sum_arr['Goodride10.00R20CR926'])?$sum_arr['Goodride10.00R20CR926']+$t2:$t2;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride10.00R20CR926']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t3 = isset($hangorder[date('m-Y',$month)]['Goodride11.00R20CR926'])?$hangorder[date('m-Y',$month)]['Goodride11.00R20CR926']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride11.00R20CR926'] = isset($sum_arr['Goodride11.00R20CR926'])?$sum_arr['Goodride11.00R20CR926']+$t3:$t3;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride11.00R20CR926']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t4 = isset($hangorder[date('m-Y',$month)]['Goodride11.00R20CR976A'])?$hangorder[date('m-Y',$month)]['Goodride11.00R20CR976A']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride11.00R20CR976A'] = isset($sum_arr['Goodride11.00R20CR976A'])?$sum_arr['Goodride11.00R20CR976A']+$t4:$t4;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride11.00R20CR976A']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t5 = isset($hangorder[date('m-Y',$month)]['Goodride11.00R20CM987'])?$hangorder[date('m-Y',$month)]['Goodride11.00R20CM987']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride11.00R20CM987'] = isset($sum_arr['Goodride11.00R20CM987'])?$sum_arr['Goodride11.00R20CM987']+$t5:$t5;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride11.00R20CM987']) ?></td>
                                </tr>
                                
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t7 = isset($hangorder[date('m-Y',$month)]['Goodride12.00R20CR926'])?$hangorder[date('m-Y',$month)]['Goodride12.00R20CR926']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride12.00R20CR926'] = isset($sum_arr['Goodride12.00R20CR926'])?$sum_arr['Goodride12.00R20CR926']+$t7:$t7;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride12.00R20CR926']) ?></td>
                                </tr>
                                
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t10 = isset($hangorder[date('m-Y',$month)]['Goodride11R22.5CR976A'])?$hangorder[date('m-Y',$month)]['Goodride11R22.5CR976A']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride11R22.5CR976A'] = isset($sum_arr['Goodride11R22.5CR976A'])?$sum_arr['Goodride11R22.5CR976A']+$t10:$t10;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride11R22.5CR976A']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t11 = isset($hangorder[date('m-Y',$month)]['Goodride11R22.5AS668'])?$hangorder[date('m-Y',$month)]['Goodride11R22.5AS668']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride11R22.5AS668'] = isset($sum_arr['Goodride11R22.5AS668'])?$sum_arr['Goodride11R22.5AS668']+$t11:$t11;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride11R22.5AS668']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t12 = isset($hangorder[date('m-Y',$month)]['Goodride11R22.5CM983'])?$hangorder[date('m-Y',$month)]['Goodride11R22.5CM983']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride11R22.5CM983'] = isset($sum_arr['Goodride11R22.5CM983'])?$sum_arr['Goodride11R22.5CM983']+$t12:$t12;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride11R22.5CM983']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t17 = isset($hangorder[date('m-Y',$month)]['Goodride295/75R22.5CR960A'])?$hangorder[date('m-Y',$month)]['Goodride295/75R22.5CR960A']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride295/75R22.5CR960A'] = isset($sum_arr['Goodride295/75R22.5CR960A'])?$sum_arr['Goodride295/75R22.5CR960A']+$t17:$t17;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride295/75R22.5CR960A']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t18 = isset($hangorder[date('m-Y',$month)]['Goodride295/75R22.5CM983'])?$hangorder[date('m-Y',$month)]['Goodride295/75R22.5CM983']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride295/75R22.5CM983'] = isset($sum_arr['Goodride295/75R22.5CM983'])?$sum_arr['Goodride295/75R22.5CM983']+$t18:$t18;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride295/75R22.5CM983']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t13 = isset($hangorder[date('m-Y',$month)]['Goodride12R22.5CR926'])?$hangorder[date('m-Y',$month)]['Goodride12R22.5CR926']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride12R22.5CR926'] = isset($sum_arr['Goodride12R22.5CR926'])?$sum_arr['Goodride12R22.5CR926']+$t13:$t13;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride12R22.5CR926']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t14 = isset($hangorder[date('m-Y',$month)]['Goodride12R22.5CR976A'])?$hangorder[date('m-Y',$month)]['Goodride12R22.5CR976A']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride12R22.5CR976A'] = isset($sum_arr['Goodride12R22.5CR976A'])?$sum_arr['Goodride12R22.5CR976A']+$t14:$t14;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride12R22.5CR976A']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t15 = isset($hangorder[date('m-Y',$month)]['Goodride12R22.5AS668'])?$hangorder[date('m-Y',$month)]['Goodride12R22.5AS668']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride12R22.5AS668'] = isset($sum_arr['Goodride12R22.5AS668'])?$sum_arr['Goodride12R22.5AS668']+$t15:$t15;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride12R22.5AS668']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t16 = isset($hangorder[date('m-Y',$month)]['Goodride12R22.5MD738'])?$hangorder[date('m-Y',$month)]['Goodride12R22.5MD738']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride12R22.5MD738'] = isset($sum_arr['Goodride12R22.5MD738'])?$sum_arr['Goodride12R22.5MD738']+$t16:$t16;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride12R22.5MD738']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t19 = isset($hangorder[date('m-Y',$month)]['Goodride12R22.5CM985'])?$hangorder[date('m-Y',$month)]['Goodride12R22.5CM985']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride12R22.5CM985'] = isset($sum_arr['Goodride12R22.5CM985'])?$sum_arr['Goodride12R22.5CM985']+$t19:$t19;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride12R22.5CM985']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t20 = isset($hangorder[date('m-Y',$month)]['Goodride12R22.5CB919'])?$hangorder[date('m-Y',$month)]['Goodride12R22.5CB919']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride12R22.5CB919'] = isset($sum_arr['Goodride12R22.5CB919'])?$sum_arr['Goodride12R22.5CB919']+$t20:$t20;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride12R22.5CB919']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t6 = isset($hangorder[date('m-Y',$month)]['Goodride11.00R20CB972'])?$hangorder[date('m-Y',$month)]['Goodride11.00R20CB972']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride11.00R20CB972'] = isset($sum_arr['Goodride11.00R20CB972'])?$sum_arr['Goodride11.00R20CB972']+$t6:$t6;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride11.00R20CB972']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t21 = isset($hangorder[date('m-Y',$month)]['Goodride12.00R20CM958'])?$hangorder[date('m-Y',$month)]['Goodride12.00R20CM958']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride12.00R20CM958'] = isset($sum_arr['Goodride12.00R20CM958'])?$sum_arr['Goodride12.00R20CM958']+$t21:$t21;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride12.00R20CM958']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t8 = isset($hangorder[date('m-Y',$month)]['Goodride12.00R20CM913A'])?$hangorder[date('m-Y',$month)]['Goodride12.00R20CM913A']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride12.00R20CM913A'] = isset($sum_arr['Goodride12.00R20CM913A'])?$sum_arr['Goodride12.00R20CM913A']+$t8:$t8;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride12.00R20CM913A']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t9 = isset($hangorder[date('m-Y',$month)]['Goodride12.00R20EZ356'])?$hangorder[date('m-Y',$month)]['Goodride12.00R20EZ356']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride12.00R20EZ356'] = isset($sum_arr['Goodride12.00R20EZ356'])?$sum_arr['Goodride12.00R20EZ356']+$t9:$t9;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride12.00R20EZ356']) ?></td>
                                </tr>
                                <tr>
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $t22 = isset($hangorder[date('m-Y',$month)]['Goodride12.00R20CB919'])?$hangorder[date('m-Y',$month)]['Goodride12.00R20CB919']:null ?></td>
                                    <?php
                                    $sum_arr['Goodride12.00R20CB919'] = isset($sum_arr['Goodride12.00R20CB919'])?$sum_arr['Goodride12.00R20CB919']+$t22:$t22;
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($sum_arr['Goodride12.00R20CB919']) ?></td>
                                </tr>
                                <tr style="font-weight: bold;">
                                    <?php
                                    $month = $minDate;
                                     while($month <= $maxDate) { ?>
                                        <td class="fix show_order"><?php echo $lib->formatMoney(array_sum($hangorder[date('m-Y',$month)])) ?></td>
                                    <?php 
                                    $tongorder += array_sum($hangorder[date('m-Y',$month)]);
                                    $month = strtotime("+1 month", $month);
                                    } ?>
                                    <td style="background-color: rgba(255, 0, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($tongorder) ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    
                    <div  style="float:left">
                        <table class="table_data_edit">
                            <thead>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <th class="fix show_going"><?php echo $tire_going->import_tire_order_code ?></th>
                                    <?php } ?>
                                    <th style="background: rgba(255, 165, 0, 0.2)" class="fix" id="show_going">Đang về</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t1 = isset($dangve[$tire_going->import_tire_order_id]['Goodride7.50R16CR926'])?$dangve[$tire_going->import_tire_order_id]['Goodride7.50R16CR926']:null ?></td>
                                    <?php
                                    $go_arr['Goodride7.50R16CR926'] = isset($go_arr['Goodride7.50R16CR926'])?$go_arr['Goodride7.50R16CR926']+$t1:$t1;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride7.50R16CR926']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t19 = isset($dangve[$tire_going->import_tire_order_id]['Goodride9.00-20CL946'])?$dangve[$tire_going->import_tire_order_id]['Goodride9.00-20CL946']:null ?></td>
                                    <?php
                                    $go_arr['Goodride9.00-20CL946'] = isset($go_arr['Goodride9.00-20CL946'])?$go_arr['Goodride9.00-20CL946']+$t19:$t19;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride9.00-20CL946']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t2 = isset($dangve[$tire_going->import_tire_order_id]['Goodride10.00R20CR926'])?$dangve[$tire_going->import_tire_order_id]['Goodride10.00R20CR926']:null ?></td>
                                    <?php
                                    $go_arr['Goodride10.00R20CR926'] = isset($go_arr['Goodride10.00R20CR926'])?$go_arr['Goodride10.00R20CR926']+$t2:$t2;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride10.00R20CR926']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t3 = isset($dangve[$tire_going->import_tire_order_id]['Goodride11.00R20CR926'])?$dangve[$tire_going->import_tire_order_id]['Goodride11.00R20CR926']:null ?></td>
                                    <?php
                                    $go_arr['Goodride11.00R20CR926'] = isset($go_arr['Goodride11.00R20CR926'])?$go_arr['Goodride11.00R20CR926']+$t3:$t3;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride11.00R20CR926']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t4 = isset($dangve[$tire_going->import_tire_order_id]['Goodride11.00R20CR976A'])?$dangve[$tire_going->import_tire_order_id]['Goodride11.00R20CR976A']:null ?></td>
                                    <?php
                                    $go_arr['Goodride11.00R20CR976A'] = isset($go_arr['Goodride11.00R20CR976A'])?$go_arr['Goodride11.00R20CR976A']+$t4:$t4;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride11.00R20CR976A']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t5 = isset($dangve[$tire_going->import_tire_order_id]['Goodride11.00R20CM987'])?$dangve[$tire_going->import_tire_order_id]['Goodride11.00R20CM987']:null ?></td>
                                    <?php
                                    $go_arr['Goodride11.00R20CM987'] = isset($go_arr['Goodride11.00R20CM987'])?$go_arr['Goodride11.00R20CM987']+$t5:$t5;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride11.00R20CM987']) ?></td>
                                </tr>
                                
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t7 = isset($dangve[$tire_going->import_tire_order_id]['Goodride12.00R20CR926'])?$dangve[$tire_going->import_tire_order_id]['Goodride12.00R20CR926']:null ?></td>
                                    <?php
                                    $go_arr['Goodride12.00R20CR926'] = isset($go_arr['Goodride12.00R20CR926'])?$go_arr['Goodride12.00R20CR926']+$t7:$t7;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride12.00R20CR926']) ?></td>
                                </tr>
                                
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t10 = isset($dangve[$tire_going->import_tire_order_id]['Goodride11R22.5CR976A'])?$dangve[$tire_going->import_tire_order_id]['Goodride11R22.5CR976A']:null ?></td>
                                    <?php
                                    $go_arr['Goodride11R22.5CR976A'] = isset($go_arr['Goodride11R22.5CR976A'])?$go_arr['Goodride11R22.5CR976A']+$t10:$t10;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride11R22.5CR976A']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t11 = isset($dangve[$tire_going->import_tire_order_id]['Goodride11R22.5AS668'])?$dangve[$tire_going->import_tire_order_id]['Goodride11R22.5AS668']:null ?></td>
                                    <?php
                                    $go_arr['Goodride11R22.5AS668'] = isset($go_arr['Goodride11R22.5AS668'])?$go_arr['Goodride11R22.5AS668']+$t11:$t11;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride11R22.5AS668']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t12 = isset($dangve[$tire_going->import_tire_order_id]['Goodride11R22.5CM983'])?$dangve[$tire_going->import_tire_order_id]['Goodride11R22.5CM983']:null ?></td>
                                    <?php
                                    $go_arr['Goodride11R22.5CM983'] = isset($go_arr['Goodride11R22.5CM983'])?$go_arr['Goodride11R22.5CM983']+$t12:$t12;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride11R22.5CM983']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t17 = isset($dangve[$tire_going->import_tire_order_id]['Goodride295/75R22.5CR960A'])?$dangve[$tire_going->import_tire_order_id]['Goodride295/75R22.5CR960A']:null ?></td>
                                    <?php
                                    $go_arr['Goodride295/75R22.5CR960A'] = isset($go_arr['Goodride295/75R22.5CR960A'])?$go_arr['Goodride295/75R22.5CR960A']+$t17:$t17;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride295/75R22.5CR960A']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t18 = isset($dangve[$tire_going->import_tire_order_id]['Goodride295/75R22.5CM983'])?$dangve[$tire_going->import_tire_order_id]['Goodride295/75R22.5CM983']:null ?></td>
                                    <?php
                                    $go_arr['Goodride295/75R22.5CM983'] = isset($go_arr['Goodride295/75R22.5CM983'])?$go_arr['Goodride295/75R22.5CM983']+$t18:$t18;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride295/75R22.5CM983']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t13 = isset($dangve[$tire_going->import_tire_order_id]['Goodride12R22.5CR926'])?$dangve[$tire_going->import_tire_order_id]['Goodride12R22.5CR926']:null ?></td>
                                    <?php
                                    $go_arr['Goodride12R22.5CR926'] = isset($go_arr['Goodride12R22.5CR926'])?$go_arr['Goodride12R22.5CR926']+$t13:$t13;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride12R22.5CR926']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t14 = isset($dangve[$tire_going->import_tire_order_id]['Goodride12R22.5CR976A'])?$dangve[$tire_going->import_tire_order_id]['Goodride12R22.5CR976A']:null ?></td>
                                    <?php
                                    $go_arr['Goodride12R22.5CR976A'] = isset($go_arr['Goodride12R22.5CR976A'])?$go_arr['Goodride12R22.5CR976A']+$t14:$t14;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride12R22.5CR976A']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t15 = isset($dangve[$tire_going->import_tire_order_id]['Goodride12R22.5AS668'])?$dangve[$tire_going->import_tire_order_id]['Goodride12R22.5AS668']:null ?></td>
                                    <?php
                                    $go_arr['Goodride12R22.5AS668'] = isset($go_arr['Goodride12R22.5AS668'])?$go_arr['Goodride12R22.5AS668']+$t15:$t15;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride12R22.5AS668']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t16 = isset($dangve[$tire_going->import_tire_order_id]['Goodride12R22.5MD738'])?$dangve[$tire_going->import_tire_order_id]['Goodride12R22.5MD738']:null ?></td>
                                    <?php
                                    $go_arr['Goodride12R22.5MD738'] = isset($go_arr['Goodride12R22.5MD738'])?$go_arr['Goodride12R22.5MD738']+$t16:$t16;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride12R22.5MD738']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t19 = isset($dangve[$tire_going->import_tire_order_id]['Goodride12R22.5CM985'])?$dangve[$tire_going->import_tire_order_id]['Goodride12R22.5C985']:null ?></td>
                                    <?php
                                    $go_arr['Goodride12R22.5CM985'] = isset($go_arr['Goodride12R22.5CM985'])?$go_arr['Goodride12R22.5CM985']+$t19:$t19;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride12R22.5CM985']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t20 = isset($dangve[$tire_going->import_tire_order_id]['Goodride12R22.5CB919'])?$dangve[$tire_going->import_tire_order_id]['Goodride12R22.5CB919']:null ?></td>
                                    <?php
                                    $go_arr['Goodride12R22.5CB919'] = isset($go_arr['Goodride12R22.5CB919'])?$go_arr['Goodride12R22.5CB919']+$t20:$t20;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride12R22.5CB919']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t6 = isset($dangve[$tire_going->import_tire_order_id]['Goodride11.00R20CB972'])?$dangve[$tire_going->import_tire_order_id]['Goodride11.00R20CB972']:null ?></td>
                                    <?php
                                    $go_arr['Goodride11.00R20CB972'] = isset($go_arr['Goodride11.00R20CB972'])?$go_arr['Goodride11.00R20CB972']+$t6:$t6;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride11.00R20CB972']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t21 = isset($dangve[$tire_going->import_tire_order_id]['Goodride12.00R20CM958'])?$dangve[$tire_going->import_tire_order_id]['Goodride12.00R20CM958']:null ?></td>
                                    <?php
                                    $go_arr['Goodride12.00R20CM958'] = isset($go_arr['Goodride12.00R20CM958'])?$go_arr['Goodride12.00R20CM958']+$t21:$t21;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride12.00R20CM958']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t8 = isset($dangve[$tire_going->import_tire_order_id]['Goodride12.00R20CM913A'])?$dangve[$tire_going->import_tire_order_id]['Goodride12.00R20CM913A']:null ?></td>
                                    <?php
                                    $go_arr['Goodride12.00R20CM913A'] = isset($go_arr['Goodride12.00R20CM913A'])?$go_arr['Goodride12.00R20CM913A']+$t8:$t8;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride12.00R20CM913A']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t9 = isset($dangve[$tire_going->import_tire_order_id]['Goodride12.00R20EZ356'])?$dangve[$tire_going->import_tire_order_id]['Goodride12.00R20EZ356']:null ?></td>
                                    <?php
                                    $go_arr['Goodride12.00R20EZ356'] = isset($go_arr['Goodride12.00R20EZ356'])?$go_arr['Goodride12.00R20EZ356']+$t9:$t9;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride12.00R20EZ356']) ?></td>
                                </tr>
                                <tr>
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $t22 = isset($dangve[$tire_going->import_tire_order_id]['Goodride12.00R20CB919'])?$dangve[$tire_going->import_tire_order_id]['Goodride12.00R20CB919']:null ?></td>
                                    <?php
                                    $go_arr['Goodride12.00R20CB919'] = isset($go_arr['Goodride12.00R20CB919'])?$go_arr['Goodride12.00R20CB919']+$t22:$t22;
                                    } ?>
                                    <td style="font-weight: bold; background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($go_arr['Goodride12.00R20CB919']) ?></td>
                                </tr>
                                <tr style="font-weight: bold;">
                                    <?php foreach ($tire_goings as $tire_going) { ?>
                                        <td class="fix show_going"><?php echo $lib->formatMoney($tire_going->import_tire_order_total) ?></td>
                                    <?php 
                                    $tongdangve+= $tire_going->import_tire_order_total;
                                    } ?>
                                    <td style="background-color: rgba(255, 165, 0, 0.2)" class="fix"><?php echo $lib->formatMoney($tongdangve) ?></td>
                                </tr>
                                <tr style="font-weight: bold;">
                                    <?php foreach ($tire_goings as $tire_going) { 
                                        if ($tire_going->import_tire_order_status==4) {
                                    ?>
                                        <td class="fix show_going"><button class="stock_going" data="<?php echo $tire_going->import_tire_order_id ?>" value="2">Cho đặt</button></td>
                                    <?php 
                                        }
                                        else{
                                    ?>
                                        <td class="fix show_going"><button class="stock_going" data="<?php echo $tire_going->import_tire_order_id ?>" value="4">Hủy đặt</button></td>
                                    <?php
                                        }
                                    } ?>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div  style="float:left">
                        <table class="table_data_edit">
                            <thead>
                                <tr>
                                    <th class="fix">Đang chờ</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride7.50R16CR926'])?$chodat['Goodride7.50R16CR926']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride9.00-20CL946'])?$chodat['Goodride9.00-20CL946']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride10.00R20CR926'])?$chodat['Goodride10.00R20CR926']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride11.00R20CR926'])?$chodat['Goodride11.00R20CR926']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride11.00R20CR976A'])?$chodat['Goodride11.00R20CR976A']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride11.00R20CM987'])?$chodat['Goodride11.00R20CM987']:null ?></td>
                                </tr>
                                
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride12.00R20CR926'])?$chodat['Goodride12.00R20CR926']:null ?></td>
                                </tr>
                                
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride11R22.5CR976A'])?$chodat['Goodride11R22.5CR976A']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride11R22.5AS668'])?$chodat['Goodride11R22.5AS668']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride11R22.5CM983'])?$chodat['Goodride11R22.5CM983']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride295/75R22.5CR960A'])?$chodat['Goodride295/75R22.5CR960A']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride295/75R22.5CM983'])?$chodat['Goodride295/75R22.5CM983']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride12R22.5CR926'])?$chodat['Goodride12R22.5CR926']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride12R22.5CR976A'])?$chodat['Goodride12R22.5CR976A']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride12R22.5AS668'])?$chodat['Goodride12R22.5AS668']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride12R22.5MD738'])?$chodat['Goodride12R22.5MD738']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride12R22.5CM985'])?$chodat['Goodride12R22.5CM985']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride12R22.5CB919'])?$chodat['Goodride12R22.5CB919']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride11.00R20CB972'])?$chodat['Goodride11.00R20CB972']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride12.00R20CM958'])?$chodat['Goodride12.00R20CM958']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride12.00R20CM913A'])?$chodat['Goodride12.00R20CM913A']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride12.00R20EZ356'])?$chodat['Goodride12.00R20EZ356']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold;" class="fix"><?php echo isset($chodat['Goodride12.00R20CB919'])?$chodat['Goodride12.00R20CB919']:null ?></td>
                                </tr>
                                <tr style="font-weight: bold;">
                                    <td class="fix"><?php echo $lib->formatMoney(array_sum($chodat)) ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div  style="float:left">
                        <table class="table_data_edit">
                            <thead>
                                <tr>
                                    <th style="background: rgba(0, 128, 0, 0.2)" class="fix">Tồn kho</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride7.50R16CR926'])?$tonkho['Goodride7.50R16CR926']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride9.00-20CL946'])?$tonkho['Goodride9.00-20CL946']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride10.00R20CR926'])?$tonkho['Goodride10.00R20CR926']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride11.00R20CR926'])?$tonkho['Goodride11.00R20CR926']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride11.00R20CR976A'])?$tonkho['Goodride11.00R20CR976A']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride11.00R20CM987'])?$tonkho['Goodride11.00R20CM987']:null ?></td>
                                </tr>
                                
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride12.00R20CR926'])?$tonkho['Goodride12.00R20CR926']:null ?></td>
                                </tr>
                                
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride11R22.5CR976A'])?$tonkho['Goodride11R22.5CR976A']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride11R22.5AS668'])?$tonkho['Goodride11R22.5AS668']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride11R22.5CM983'])?$tonkho['Goodride11R22.5CM983']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride295/75R22.5CR960A'])?$tonkho['Goodride295/75R22.5CR960A']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride295/75R22.5CM983'])?$tonkho['Goodride295/75R22.5CM983']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride12R22.5CR926'])?$tonkho['Goodride12R22.5CR926']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride12R22.5CR976A'])?$tonkho['Goodride12R22.5CR976A']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride12R22.5AS668'])?$tonkho['Goodride12R22.5AS668']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride12R22.5MD738'])?$tonkho['Goodride12R22.5MD738']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride12R22.5CM985'])?$tonkho['Goodride12R22.5CM985']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride12R22.5CB919'])?$tonkho['Goodride12R22.5CB919']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride11.00R20CB972'])?$tonkho['Goodride11.00R20CB972']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride12.00R20CM958'])?$tonkho['Goodride12.00R20CM958']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride12.00R20CM913A'])?$tonkho['Goodride12.00R20CM913A']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride12.00R20EZ356'])?$tonkho['Goodride12.00R20EZ356']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo isset($tonkho['Goodride12.00R20CB919'])?$tonkho['Goodride12.00R20CB919']:null ?></td>
                                </tr>
                                <tr style="font-weight: bold;">
                                    <td style="background-color: rgba(0, 128, 0, 0.2)" class="fix"><?php echo $lib->formatMoney(array_sum($tonkho)) ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div  style="float:left">
                        <table class="table_data_edit">
                            <thead>
                                <tr>
                                    <th style="background: rgba(0, 0, 255, 0.2)" class="fix">Đặt hàng</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride7.50R16CR926'])?$dathang['Goodride7.50R16CR926']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride9.00-20CL946'])?$dathang['Goodride9.00-20CL946']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride10.00R20CR926'])?$dathang['Goodride10.00R20CR926']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride11.00R20CR926'])?$dathang['Goodride11.00R20CR926']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride11.00R20CR976A'])?$dathang['Goodride11.00R20CR976A']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride11.00R20CM987'])?$dathang['Goodride11.00R20CM987']:null ?></td>
                                </tr>
                                
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride12.00R20CR926'])?$dathang['Goodride12.00R20CR926']:null ?></td>
                                </tr>
                                
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride11R22.5CR976A'])?$dathang['Goodride11R22.5CR976A']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride11R22.5AS668'])?$dathang['Goodride11R22.5AS668']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride11R22.5CM983'])?$dathang['Goodride11R22.5CM983']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride295/75R22.5CR960A'])?$dathang['Goodride295/75R22.5CR960A']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride295/75R22.5CM983'])?$dathang['Goodride295/75R22.5CM983']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride12R22.5CR926'])?$dathang['Goodride12R22.5CR926']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride12R22.5CR976A'])?$dathang['Goodride12R22.5CR976A']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride12R22.5AS668'])?$dathang['Goodride12R22.5AS668']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride12R22.5MD738'])?$dathang['Goodride12R22.5MD738']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride12R22.5CM985'])?$dathang['Goodride12R22.5CM985']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride12R22.5CB919'])?$dathang['Goodride12R22.5CB919']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride11.00R20CB972'])?$dathang['Goodride11.00R20CB972']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride12.00R20CM958'])?$dathang['Goodride12.00R20CM958']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride12.00R20CM913A'])?$dathang['Goodride12.00R20CM913A']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride12.00R20EZ356'])?$dathang['Goodride12.00R20EZ356']:null ?></td>
                                </tr>
                                <tr>
                                    <td style="font-weight: bold; background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo isset($dathang['Goodride12.00R20CB919'])?$dathang['Goodride12.00R20CB919']:null ?></td>
                                </tr>
                                <tr style="font-weight: bold;">
                                    <td style="background-color: rgba(0, 0, 255, 0.2)" class="fix"><?php echo $lib->formatMoney(array_sum($dathang)) ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            
</div>

<script type="text/javascript">
    $('#show_order').toggle(function(){
        $('.show_order').show();
    },function(){
        $('.show_order').hide();
    });
    $('#show_going').toggle(function(){
        $('.show_going').show();
    },function(){
        $('.show_going').hide();
    });

$('.stock_going').click(function(){
    var data = $(this).attr('data');
    var val = $(this).attr('value');
    $.post("<?php echo BASE_URL ?>/stockanalytics/going", {data: data, value: val},
       function(data){
        setTimeout(function() {
            sapxep('1','','');
          }, 200);
       
       }); 
});
</script>

<style type="text/css">
.report{
    width: 100%;
    margin: 5px auto;
}
.report-left{
    float: left;
    width: 200px;
    margin-right:15px;
}
.report-right{
    width: 100%;
}
.report-right td{
    height: 39px;
    text-align: right;
}
.show_order, .show_going{
    display: none;
}
.table_data_edit {
border-color: #d1e5ee;
background-color: #fff;
border-spacing: 0;
width: 100%;
margin: 0;
-webkit-border-radius: 3px;
border-radius: 3px;
-moz-border-radius: 3px;
border-width: 1px;
border-style: solid;
}
.table_data_edit thead tr th.fix{
text-align: center;
border:1px solid;
}
.table_data_edit thead tr th {
background: #f5fafd;
background-image: -webkit-gradient(linear,left bottom,left top,from(#eff8ff),to(#f7fcfe));
background-image: -webkit-linear-gradient(bottom,#eff8ff,#f7fcfe);
background-image: -moz-linear-gradient(bottom,#eff8ff,#f7fcfe);
background-image: -o-linear-gradient(bottom,#eff8ff,#f7fcfe);
background-image: linear-gradient(to top,#eff8ff,#f7fcfe);
padding: 5px;
color: #21759b;
text-align: left;
cursor: pointer;
}
.table_data_edit td {
border-top: 1px solid #80C8E5;
padding: 4px;
vertical-align: middle;
line-height: inherit;
overflow: hidden;
}
.table_data_edit tbody tr td.fix {
    border-right: 1px dotted #21759b;
}
.table_data_edit tr:nth-child(even) {background: rgba(255, 240, 250, 0.59)}
.table_data_edit tr:nth-child(odd) {background: #FFF}
.table_data_edit tr:hover{background: rgba(68, 157, 245, 0.56); cursor: pointer;}
</style>