<table>
  <tr>
    <td>Ngày đặt hàng:</td>
    <td><b><?php echo $lib->hien_thi_ngay_thang($order_tire->order_tire_date); ?></b></td>
  </tr>
  <tr>
    <td>Tên KH:</td>
    <td><b><?php echo $customers->customer_name ?></b></td>
  </tr>
  <tr>
    <td>Công ty:</td>
    <td><b><?php echo $customers->company_name ?></b></td>
  </tr>
  <tr>
    <td>MST:</td>
    <td><b><?php echo $customers->mst ?></b></td>
  </tr>
  <tr>
    <td>ĐC:</td>
    <td><b><?php echo $customers->customer_address ?></b></td>
  </tr>
  <tr>
    <td>Sale:</td>
    <td><b><?php echo $sale ?></b></td>
  </tr>
</table>

<?php $l=1 ; $tong=0; ?>
<table class="table_data" id="or">
<thead>
    <tr>
        <th class="fix">
            <a class="sort">STT</a>
        </th>
        <th  class="fix">
            <a class="sort " >Tên hàng </a>
        </th>
        <th  class="fix">
            <a class="sort " >Loại hàng </a>
        </th>
        <th  class="fix">
            <a class="sort " >Đơn vị </a>
        </th>
        <th  class="fix">
            <a class="sort " >Số lượng </a>
        </th>
        <th  class="fix">
            <a class="sort " >Đơn giá </a>
        </th>
        <th  class="fix">
            <a class="sort " >Thành tiền </a>
        </th>
    </tr>
    
   </thead>
   <tbody>
    <?php foreach ($order_tire_lists as $order_tire_list) : 
        $tong += $order_tire_list->tire_number;
        $dongia = $order_tire->check_price_vat==1?$order_tire_list->tire_price_vat:$order_tire_list->tire_price;
        $thanhtien = $dongia*$order_tire_list->tire_number;
    ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $order_tire_list->order_tire_list_id ?>" class="edit_tr" data="<?php echo $order_tire->sale_lock ?>" >
            <td class="fix text-center"><?php echo $l++; ?></td>
            <td class="fix text-center" data="<?php echo $order_tire_list->tire_brand; ?>"  id="tire_brand_<?php echo $order_tire_list->order_tire_list_id; ?>"><?php echo $order_tire_list->tire_brand_name; ?></td>
            <td class="fix text-center" data="<?php echo $order_tire_list->tire_size; ?>" id="tire_size_<?php echo $order_tire_list->order_tire_list_id; ?>"><?php echo $order_tire_list->tire_size_number.' '.$order_tire_list->tire_pattern_name; ?></td>
            <td class="fix text-center" data="<?php echo $order_tire_list->tire_pattern; ?>" id="tire_pattern_<?php echo $order_tire_list->order_tire_list_id; ?>"><?php echo substr($order_tire_list->tire_size_number, -2)=='.5'?'Cái':'Bộ';  ?></td>
            <td class="fix text-center"  id="tire_number_<?php echo $order_tire_list->order_tire_list_id; ?>"><?php echo $order_tire_list->tire_number; ?></td>
            <td class="fix text-right"  id="tire_price_<?php echo $order_tire_list->order_tire_list_id; ?>"><?php echo $lib->formatMoney($dongia); ?></td>
            <td class="fix text-right"  id="tt_<?php echo $order_tire_list->order_tire_list_id; ?>"><?php echo $lib->formatMoney($thanhtien); ?></td>
            
        </tr>
    <?php endforeach; 
    if ($order_tire->check_price_vat!=1) {
    ?>
    <tr>
      <td class="fix text-center" colspan="4">VAT</td>
      <td class="fix text-center" colspan="2" ><?php echo $order_tire->vat_percent.'%'; ?></td>
      <td class="fix text-right" ><?php echo $lib->formatMoney($order_tire->vat); ?></td>
    </tr>
    <?php
    }
    $ck = $order_tire->discount+$order_tire->reduce;
    if ($ck!=0) {
    ?>
    <tr>
      <td class="fix text-center" colspan="4">Chiết khấu</td>
      <td class="fix" colspan="2" ></td>
      <td class="fix text-right" ><?php echo $lib->formatMoney($ck); ?></td>
    </tr>
    <?php
    }
    if ($order_tire->warranty!=0) {
    ?>
    <tr>
      <td class="fix text-center" colspan="4">Bảo hành</td>
      <td class="fix" colspan="2" ></td>
      <td class="fix text-right" ><?php echo $lib->formatMoney($order_tire->warranty); ?></td>
    </tr>
    <?php
    }
    ?>
    <tr style="text-align:center; font-weight: bold; color: red;">
        <td class="fix" colspan="4" >Tổng thanh toán</td>
        <td class="fix"><?php echo $lib->formatMoney($tong); ?></td>
        <td class="fix" ></td>
        <td class="fix text-right" ><?php echo $lib->formatMoney($order_tire->total); ?></td>
    </tr>
   </tbody>
</table>

<?php
if ($order_tire->check_price_vat==1) {
  echo '<i class="error">* Đơn giá đã bao gồm VAT '.$order_tire->vat_percent.'%</i>';
}
?>

