
<?php 
$lock = 0;
$check_date = $order_tire->order_tire_status==1?(strtotime(date('t-m-Y',$order_tire->delivery_date))+691200):(strtotime(date('t-m-Y'))+691200); 
$today = strtotime(date('d-m-Y'));
if ($_SESSION['role_logined'] != 1 && $_SESSION['role_logined'] != 9 && $_SESSION['role_logined'] != 3  && $_SESSION['role_logined'] != 2  && $_SESSION['role_logined'] != 8) { 
  if ($today > $check_date) {
    $lock = 1;
  }
}
if ($order_tire->sale_lock != 1) {
  $lock=0;
}
?>
<div>
    <div <?php echo $lock==1?'style="display:none"':null ?> class="add-box"><a class="add_button" onClick="add_click();">Thêm</a></div>
</div>

<?php $l=1 ; $tong=0; $dachi=0; ?>
<table class="table_data" id="or">
<thead>
    <tr>
      <th class="fix">
            <a class="sort">STT</a>
        </th>
        <th class="fix">
            <a class="sort">Chi phí</a>
        </th>
        <th  class="fix">
            <a class="sort " >Vendor </a>
        </th>
        <th  class="fix">
            <a class="sort " >Nội dung </a>
        </th>
        <th  class="fix">
            <a class="sort " >Số tiền </a>
        </th>
        <th  class="fix">
            <a class="sort " >Đã chi </a>
        </th>
        <th  class="fix">
            <a class="sort " >Ngày chi </a>
        </th>
        <th  class="fix">
            <a class="sort " >Đề nghị </a>
        </th>
           
        <th  class="fix">&nbsp;</th>
    </tr>
    
   </thead>
   <tbody>
    <?php foreach ($order_tire_costs as $order_tire_cost) : 
        $tong += $order_tire_cost->order_tire_cost;
        $dachi += isset($pay_data[$order_tire_cost->order_tire_cost_id]['money'])?$pay_data[$order_tire_cost->order_tire_cost_id]['money']:0;
    ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $order_tire_cost->order_tire_cost_id ?>" class="edit_tr" data="<?php echo $lock ?>" alt="<?php echo $order_tire->sale_lock ?>" >
            <td class="fix"><?php echo $l++; ?></td>
            <td class="fix" data="<?php echo $order_tire_cost->order_tire_cost_type; ?>"  id="order_tire_cost_type_<?php echo $order_tire_cost->order_tire_cost_id; ?>">
              <?php
              switch ($order_tire_cost->order_tire_cost_type) {
                case '1':
                  echo 'Trucking';
                  break;
                case '2':
                  echo 'Barging';
                  break;
                case '3':
                  echo 'Feeder';
                  break;
                case '4':
                  echo 'Thu hộ';
                  break;
                case '5':
                  echo 'Hoa hồng';
                  break;
                case '6':
                  echo 'TTHQ';
                  break;
                default:
                  echo 'Khác';
                  break;
              }
              ?>
            </td>
            <td class="fix" data="<?php echo $order_tire_cost->vendor; ?>" id="vendor_<?php echo $order_tire_cost->order_tire_cost_id; ?>"><?php echo $order_tire_cost->shipment_vendor_name; ?></td>
            <td class="fix"  id="comment_<?php echo $order_tire_cost->order_tire_cost_id; ?>"><?php echo $order_tire_cost->comment; ?></td>
            <td class="fix"  id="order_tire_cost_<?php echo $order_tire_cost->order_tire_cost_id; ?>"><?php echo $lib->formatMoney($order_tire_cost->order_tire_cost); ?></td>
            <td class="fix"  id="order_tire_pay_money_<?php echo $order_tire_cost->order_tire_cost_id; ?>"><?php echo isset($pay_data[$order_tire_cost->order_tire_cost_id]['money'])?$lib->formatMoney($pay_data[$order_tire_cost->order_tire_cost_id]['money']):null; ?></td>
            <td class="fix"  id="order_tire_cost_paydate_<?php echo $order_tire_cost->order_tire_cost_id; ?>"><?php echo isset($pay_data[$order_tire_cost->order_tire_cost_id]['date'])?$lib->hien_thi_ngay_thang($pay_data[$order_tire_cost->order_tire_cost_id]['date']):null; ?></td>
            <td class="fix"  id="order_tire_cost_create_user_<?php echo $order_tire_cost->order_tire_cost_id; ?>"><?php echo $pay_data[$order_tire_cost->order_tire_cost_id]['user']; ?></td>
            <td style="display: none" id="order_tire_cost_date_<?php echo $order_tire_cost->order_tire_cost_id; ?>"><?php echo date('d-m-Y',$order_tire_cost->order_tire_cost_date) ?></td>
            <td>
                <?php if(!isset($pay_data[$order_tire_cost->order_tire_cost_id]['money']) || $_SESSION['role_logined']==1){ ?>
                <button class="del_list" data="<?php echo $order_tire_cost->order_tire_cost_id ?>" style="display:block">Xóa</button>
                <?php } ?>
            </td>
        </tr>
    <?php endforeach; ?>
    <tr style="text-align:center; font-weight: bold; color: red;">
        <td class="fix" colspan="4" >Tổng cộng</td>
        <td class="fix"><?php echo $lib->formatMoney($tong); ?></td>
        <td class="fix"><?php echo $lib->formatMoney($dachi); ?></td>
        <td class="fix" colspan="2" ></td>
    </tr>
   </tbody>
</table>

<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

<div class="add-field">
        <fieldset class="groupbox">
            <legend>
                <span><h3>Chi phí </h3></span>
            </legend>
            <div class="login_body">
                  <form id="add_customer" method="post" action="">
                      <table style="margin:0 auto;width:100%">
                        <tr>
                            <td>
                              <span class="add-on"><i class="icon-company" ></i></span>
                              <span>Loại chi phí: </span>
                            </td>
                            <td>
                              <select style="width: 120px" class="order_tire_cost_type" name="order_tire_cost_type" id="order_tire_cost_type" disabled>
                                <option value="1">Trucking</option>
                                <option value="2">Barging</option>
                                <option value="3">Feeder</option>
                                <option value="4">Thu hộ</option>
                                <option value="5">Hoa hồng</option>
                                <option value="6">TTHQ</option>
                                <option value="7">Khác</option>
                              </select>
                            </td>
                          </tr>
                          <tr>
                            <td>
                              <span class="add-on"><i class="icon-resize-full" ></i></span>
                              <span>Vendor: </span>
                            </td>
                            <td><input type="text" id="vendor" class="vendor" name="vendor" value="" disabled required="required" autocomplete="off" />
                              <ul class="customer_list_id"></ul>
                            </td>
                          </tr>
                          <tr>
                            <td>
                              <span class="add-on"><i class="icon-barcode" ></i></span>
                              <span>Nội dung: </span>
                            </td>
                            <td><input type="text" id="comment" class="comment" name="comment" value="" disabled required="required" autocomplete="off" />
                            </td>
                          </tr>
                          <tr>
                            <td>
                              <span class="add-on"><i class="icon-th-list" ></i></span>
                              <span>Số tiền: </span>
                            </td>
                            <td><input type="text" id="order_tire_cost" name="order_tire_cost" value="" class="numbers" disabled required="required" /></td>
                          </tr>
                          <tr>
                            <td>
                              <span class="add-on"><i class="icon-clock-o" ></i></span>
                              <span>Ngày: </span>
                            </td>
                            <td><input type="text" id="order_tire_cost_date" name="order_tire_cost_date" value="" class="ngay" disabled required="required" /></td>
                          </tr>
                        <tr>
                            <td>
                              <input type="hidden" readonly id="yes" name="yes" required="required" >
                              <input type="hidden" readonly id="order" name="order" required="required" value="<?php echo $order ?>" >
                            </td>
                        </tr>
                         <tr>
                            <td><input type="submit" name="submit" id="submit_list" value="Hoàn tất" disabled tabindex="1"></td>
                            <td ><input type="reset" name="reset" id="reset_list" value="Nhập lại" disabled tabindex="2"></td>
                             
                        </tr>
                    </table> 
                </form>
            </div>
        </fieldset>
    </div>
<script type="text/javascript">

$('html').click(function(e) {
    if(e.target == '[object HTMLDivElement]' || e.target == '[object HTMLBodyElement]') {
        $('.add-field').slideUp(500);    
    }
    $('.customer_list_id').slideUp(200);
});
    $('.edit_tr').click(function(e){
            if(!$('.checkbox').is(':checked') && e.target == '[object HTMLButtonElement]'){
                $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
            }
            var order_tire_cost_type_name = $(this).find("#order_tire_cost_type_"+$(this).attr('id')).text();
            var order_tire_cost_type = $(this).find("#order_tire_cost_type_"+$(this).attr('id')).attr('data');
            var vendor_name = $(this).find("#vendor_"+$(this).attr('id')).text();
            var vendor = $(this).find("#vendor_"+$(this).attr('id')).attr('data');
            var comment = $(this).find("#comment_"+$(this).attr('id')).text();
            var order_tire_cost = $(this).find("#order_tire_cost_"+$(this).attr('id')).text();
            var order_tire_cost_date = $(this).find("#order_tire_cost_date_"+$(this).attr('id')).text();
            
            //alert(customer_code);
            $('#yes').val($(this).attr('id'));
            
            
            
            $('#order_tire_cost_type option[value='+order_tire_cost_type+']').attr('selected','selected');
            $('#vendor').val(vendor_name);
            $('#vendor').attr('data',vendor);
            $('#comment').val(comment);
            $('#order_tire_cost').val(order_tire_cost);
            $('#order_tire_cost_date').val(order_tire_cost_date);

            if ($(this).attr('data')!=1 || $(this).attr('alt')!=1  || 1=="<?php echo $_SESSION['role_logined'] ?>") {
              $('#order_tire_cost_type').attr('disabled',false);
              $('#vendor').attr('disabled',false);
              $('#comment').attr('disabled',false);
              $('#order_tire_cost_date').attr('disabled',false);
              $('#order_tire_cost').attr('disabled',false);
              $('#submit_list').attr('disabled',false);
              $('#reset_list').attr('disabled',false);
              $('#tire_date').attr('disabled',false);
            }


    });

function add_click(){
  $('#yes').val("");
  $('.add-field').slideDown(500);
  $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);  

  $('#vendor').val("");
  $('#vendor').attr('data',"");
  $('#comment').val("");
  $('#order_tire_cost_date').val("<?php echo date('d-m-Y') ?>");
  $('#order_tire_cost').val("");

  
    $('#order_tire_cost_type').attr('disabled',false);
    $('#vendor').attr('disabled',false);
    $('#comment').attr('disabled',false);
    $('#order_tire_cost_date').attr('disabled',false);
    $('#order_tire_cost').attr('disabled',false);
    $('#submit_list').attr('disabled',false);
    $('#reset_list').attr('disabled',false);
    $('#tire_date').attr('disabled',false);
  


}

</script>
<script type="text/javascript">


$(document).ready(function(){
            // Validate form
            $("#add_customer").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    var order_tire_cost_type = $('#order_tire_cost_type').attr('value');
                    var vendor = $('#vendor').attr('data');
                    var comment = $('#comment').attr('value');
                    var order_tire_cost_date = $('#order_tire_cost_date').attr('value');
                    var order_tire_cost = $('#order_tire_cost').attr('value');
                    var order = $('#order').attr('value');

                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/ordertire/editordercost", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            order_tire_cost_type: order_tire_cost_type,
                            vendor: vendor,
                            comment: comment,
                            order_tire_cost_date: order_tire_cost_date,
                            order_tire_cost: order_tire_cost,
                            order: order,
                            yes: yes,
                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            //alert(answer);
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                $('#order_tire_cost_'+yes).text(order_tire_cost);
                            }
                            else{
                            }
                        }
                    });
                    return false;
                     
                 }
            });
   
   
   

   $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9]/g, "")
        ;
      });
    });

   $('.numbers').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.numbers').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });

         $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });
    
  $('.vendor').keyup(function(){
    var rowIndex = 0;

    var keyword = $(this).val();
    $.ajax({
        url: '<?php echo BASE_URL ?>/ordertire/getvendor',
        type: 'POST',
        data: {keyword:keyword, offset:rowIndex},
        success:function(data){
            $('.customer_list_id:eq('+rowIndex+')').slideDown(200);
            $('.customer_list_id:eq('+rowIndex+')').html(data);
        }
    });
    if ($('.vendor:eq('+rowIndex+')').val() == "" || $('.vendor:eq('+rowIndex+')').attr('data') == "") {
        
        $('.vendor:eq('+rowIndex+')').attr('data',"");
    }

    
});

$('.vendor').on('keydown', function() {
    var rowIndex = 0;

    var key = event.keyCode || event.charCode;

    if( key == 8 || key == 46 ){
        $('.vendor:eq('+rowIndex+')').attr('data',"");
    }
        
  });
function set_item_other(item,value,vitri) {
    // change input value
    $('.vendor:eq('+vitri+')').val(item);
    $('.vendor:eq('+vitri+')').attr("data",value);
    // hide proposition list
    $('.customer_list_id').hide();
    $('.vendor:eq('+vitri+')').focus();

    var check_type = 0;
    var check_vendor = 0;
    var val = value;
    var type_val = $('.order_tire_cost_type:eq('+vitri+')').val();
        $('.vendor').each(function() { 
            if (val == $(this).attr('data')) {
                check_vendor ++;

                var row2 = $(this).parent().parent().parent().parent().parent().parent();
                var rowIndex2 = row2[0].rowIndex;
                var type_val2 = $('.order_tire_cost_type:eq('+rowIndex2+')').val();
                if (type_val == type_val2) {
                    check_type ++;
                }
            }
        });


        if (check_type >= 2 && check_vendor >= 2) {
            alert('Vui lòng chọn loại phí khác cho vendor này!');
            $(".order_tire_cost_type:last").val($(".order_tire_cost_type:last option:first").val());
            //$(".vendor:last").val($(".vendor:last option:first").val());
            $('.vendor:last').attr('data','');
            $('.vendor:last').val("");
            
        };
}

});
function get_number(id){
    return $(id).val().replace(/\,/g,'');
}


var pickerOpay2 = {
      closeText: "Đóng",
      currentText: "Hiện tại",
      nextText: "Tiếp",
      prevText: "Quay lại",
      monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
      monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
      dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
      dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
      dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
      dateFormat: 'dd-mm-yy',
      changeMonth: true,
      changeYear: true,
      yearRange: "-100:+0",
      firstDay: 1,
      isRTL: false,
      showButtonPanel: true
  }; 
  $(".ngay").datepicker(pickerOpay2);
</script>
</div>

<script type="text/javascript">
$('.del_list').click(function(){
    var id = $(this).attr('data');
    var r = confirm("Bạn có chắc chắn muốn xóa không?");
      if (r == true){
        $('#loading').html("<img src='public/images/loading.gif'/>").fadeIn(500);
        $.post("<?php echo BASE_URL ?>/ordertire/deleteordercost", {data: id},
           function(data){
            //alert(data);
            if (data.trim() != 'Bạn không có quyền thực hiện thao tác này') {
              $('#or tr#'+id).remove(); 
              $('#loading').fadeOut(500); 
            };
            $('#loading').fadeOut(500);
           
           }); 
      }
});


</script>